---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: blog
  label: Blog
  create: all
  match: "**/*"
- type: document
  path: about/_index.md
  label: About
- type: document
  path: contact/_index.md
  label: Contact
upload_dir: blockchainhubprague.com/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.53'
