---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -D
  publish_command: hugo -b
  publish_env:
  - do_it=now
  output_directory: public
version: '0.53'
